# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170424_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='shop/photos', verbose_name='фотография'),
        ),
    ]
